test "item durability":
	set {_i} to a diamond sword
	set durability of {_i} to 500
	assert durability of {_i} = 500 with "Durability of item should have been 500"

# This SHOULD be 'when minecraft version is not "1.13"' but there seems to be a bug with versions in tests
# This technically should test 1.12.2 and above, but for some reason its not
# Luckily we only want to test this on 1.12.2 and below, so this bug is working in our favor
test "block data value" when minecraft version is "1.12.2":
	set block at spawn of world "world" to farmland
	set {_b} to block above block at spawn of world "world"
	set block at {_b} to fully grown wheat plant
	assert data value of block at {_b} = 7 with "Data value of block should have been 7"
	set data value of block at {_b} to 1
	assert data value of block at {_b} = 1 with "Data value of block should have been 1"
