test "chunk/world is loaded":
	#Chunks
	assert chunk at spawn of world "world" is loaded with "chunk at spawn should have been loaded"
	set block at location(16, 1, 16, world "world") to dirt
	assert chunk at 1, 1 in world "world" is loaded with "chunk at 1, 1 in world should have been loaded"
	assert chunk at location(16, 1, 16, world "world") is loaded with "chunk at location(1, 1, 1, world ""world"") should be loaded"
	assert chunk at 1000, 1000 in world "world" is not loaded with "chunk at 1000, 1000 in world should not have been loaded"
	assert chunk at location(1000, 1, 1000, world "world") is not loaded with "chunk at location(1000, 1, 1000, world ""world"") should not be loaded"

	#World
	assert world("world") is loaded with "world ""world"" should have been loaded"
	assert world("fake-world") is not loaded with "world ""fake-world"" should not have been loaded"
