test "large numbers in list indices":
	set {_l::999999999999999999999999999999999999999999999} to 3
	assert {_l::888888888888888888888888888888888888888888} isn't set with "Two large numbers in variable indices were treated as equal"

test "order of numerical list indices":
	set {_l::-0.99} to 1
	set {_l::-0.51} to 2
	set {_l::-0.5} to 3
	set {_l::-0.49} to 4
	set {_l::-0.4} to 5
	set {_l::0.0} to 6
	set {_l::0.01} to 7
	set {_l::0.1} to 8
	set {_l::0.12} to 9
	set {_l::0.69} to 10

	set {_i} to 1
	loop {_l::*}:
		loop-value is {_i}
		add 1 to {_i}
