function myFunction_five_nine_zero(s: string) :: string:
	return {_s}

test "double quote parsing":
	assert "Testing" is set with "simple string failed"

	assert "Testing %1 + 1%" is set with "simple string with expression failed"

	assert "Testing """ is set with "simple string with escaped quote failed"

	assert "Testing %length of "abc"%" is set with "string with expression with string ##1 failed"
	assert "%myFunction_five_nine_zero("Hello")% world" is "Hello world" with "string with expression with string ##2 failed"


	assert {_abc} is not set with "simple variable failed"
	assert {_abc%%} is not set with "simple variable with escaped percentage sign failed"
	assert {_abc%1 + 1%} is not set with "simple variable with expression failed"

	assert {_%subtext of "test" from characters 1 to 1%} is not set with "variable with expression with string failed"
