#
#   This file is part of Skript.
#
#  Skript is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.
#
#  Skript is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with Skript.  If not, see <http://www.gnu.org/licenses/>.
#
# Copyright Peter Güttinger, SkriptLang team and contributors
#


name: Skript

description: Customize Minecraft's mechanics with simple scripts written in plain English sentences.

authors:
    - Njol
    - Mirreski
    - bensku
    - TheBentoBox
    - FranKusmiruk
    - ShaneBeee
    - Blueyescat
    - JRoy
    - Nicofisi
    - APickledWalrus
    - xXAndrew28Xx
    - Syst3ms
    - TheLimeGlass
    - Pikachu920
    - Sashie
    - Wealthyturtle
    - OfficialDonut
    - eyesniper2

website: https://skriptlang.github.io/Skript

main: ch.njol.skript.Skript

version: @version@
api-version: 1.13

commands:
    skript:
        description: Skript's main command. Type '/skript help' for more information.
        aliases: [sk]
        permission: skript.admin
        usage: /skript help

softdepend: [SQLibrary, Vault, WorldGuard, Residence, PreciousStones]

permissions:
    skript.*:
        default: false
        children:
            skript.effectcommands: true
            skript.admin: true
            #skript.config: true
    skript.effectcommands:
        default: false
        description: Allows to use effects as commands, e.g. '!set health to 10'
    skript.admin:
        default: op
        description: Allows to use administrative commands and to recieve notifications of new versions.
#    skript.config:
#        description: allows to modify the configuration files via commands
#        default: false
